const UPDATABLE_FIELDS: Record<string, string[]> = {
  account: [
    'additionalEmailAddresses',
    'autoPay',
    'batch',
    'billCycleDay',
    'billToContact',
    'billToContactId',
    'communicationProfileId',
    'creditMemoTemplateId',
    'crmId',
    'customerServiceRepName',
    'debitMemoTemplateId',
    'defaultPaymentMethodId',
    'einvoiceProfile',
    'gatewayRoutingEligible',
    'invoiceDeliveryPrefsEmail',
    'invoiceDeliveryPrefsPrint',
    'invoiceTemplateId',
    'name',
    'notes',
    'parentId',
    'partnerAccount',
    'paymentGateway',
    'paymentTerm',
    'profileNumber',
    'purchaseOrderNumber',
    'salesRep',
    'sequenceSetId',
    'shipToContact',
    'shipToContactId',
    'soldToContact',
    'soldToContactId',
    'tagging',
    'summaryStatementTemplateId',
    'taxInfo',
    'Class__NS',
    'CustomerType__NS',
    'Department__NS',
    'IntegrationId__NS',
    'IntegrationStatus__NS',
    'Location__NS',
    'Subsidiary__NS',
    'SyncDate__NS',
    'SynctoNetSuite__NS',
  ],
  'order-line-item': [
    'UOM',
    'accountingCode',
    'adjustmentLiabilityAccountingCode',
    'adjustmentRevenueAccountingCode',
    'amountPerUnit',
    'billTargetDate',
    'billTo',
    'billingRule',
    'contractAssetAccountingCode',
    'contractLiabilityAccountingCode',
    'contractRecognizedRevenueAccountingCode',
    'customFields',
    'deferredRevenueAccountingCode',
    'description',
    'excludeItemBillingFromRevenueAccounting',
    'excludeItemBookingFromRevenueAccounting',
    'inlineDiscountPerUnit',
    'inlineDiscountType',
    'isAllocationEligible',
    'isUnbilled',
    'itemName',
    'itemState',
    'itemType',
    'listPricePerUnit',
    'ownerAccountNumber',
    'productCode',
    'purchaseOrderNumber',
    'quantity',
    'recognizedRevenueAccountingCode',
    'relatedSubscriptionNumber',
    'revenueRecognitionRule',
    'revenueRecognitionTiming',
    'revenueAmortizationMethod',
    'invoiceGroupNumber',
    'sequenceSetId',
    'paymentTerm',
    'invoiceTemplateId',
    'shipTo',
    'soldTo',
    'taxCode',
    'taxMode',
    'transactionEndDate',
    'transactionStartDate',
    'unbilledReceivablesAccountingCode',
  ],
  invoice: [
    'autoPay',
    'autoPayAmount',
    'comments',
    'dueDate',
    'invoiceDate',
    'paymentTerm',
    'transferredToAccounting',
  ],
  'credit-memo': [
    'autoApplyUponPosting',
    'comment',
    'creditMemoDate',
    'excludeFromAutoApplyRules',
    'reasonCode',
    'transferredToAccounting',
  ],
  'debit-memo': [
    'autoPay',
    'comment',
    'debitMemoDate',
    'dueDate',
    'paymentTerm',
    'reasonCode',
    'transferredToAccounting',
  ],
  contact: [
    'address1',
    'address2',
    'city',
    'contactDescription',
    'country',
    'county',
    'fax',
    'firstName',
    'homePhone',
    'lastName',
    'mobilePhone',
    'nickname',
    'otherPhone',
    'otherPhoneType',
    'personalEmail',
    'state',
    'taxRegion',
    'workEmail',
    'workPhone',
    'zipCode',
  ],
  subscription: [
    'autoRenew',
    'currentTerm',
    'currentTermPeriodType',
    'invoiceSeparately',
    'notes',
    'renewalSetting',
    'renewalTerm',
    'renewalTermPeriodType',
    'termType',
  ],
  order: [
    'category',
    'description',
    'orderDate',
    'reasonCode',
  ],
  product: [
    'AllowFeatureChanges',
    'Category',
    'Description',
    'EffectiveEndDate',
    'EffectiveStartDate',
    'Name',
    'SKU',
  ],
  'product-rate-plan': [
    'Description',
    'EffectiveEndDate',
    'EffectiveStartDate',
    'Name',
  ],
  'product-rate-plan-charge': [
    'AccountingCode',
    'BillCycleDay',
    'BillCycleType',
    'BillingPeriod',
    'BillingPeriodAlignment',
    'BillingTiming',
    'DefaultQuantity',
    'Description',
    'DeferredRevenueAccount',
    'EndDateCondition',
    'IncludedUnits',
    'MaxQuantity',
    'MinQuantity',
    'Name',
    'NumberOfPeriod',
    'OverageCalculationOption',
    'OverageUnusedUnitsCreditOption',
    'PriceChangeOption',
    'PriceIncreasePercentage',
    'RecognizedRevenueAccount',
    'RevenueRecognitionRuleName',
    'SmoothingModel',
    'SpecificBillingPeriod',
    'TaxCode',
    'TaxMode',
    'Taxable',
    'TriggerEvent',
    'UOM',
    'UpToPeriodsType',
    'UpToPeriods',
    'UsageRecordRatingOption',
    'UseDiscountSpecificAccountingCode',
    'UseTenantDefaultForPriceChange',
    'WeeklyBillCycleDay',
  ],
  // workflow, billing-template: TBD — pass through unfiltered until defined
};

export function filterUpdatableFields(
  resource: string,
  data: Record<string, unknown>
): Record<string, unknown> {
  const allowed = UPDATABLE_FIELDS[resource];
  const entries = allowed
    ? Object.entries(data).filter(([key]) => new Set(allowed).has(key) || key.endsWith('__c'))
    : Object.entries(data);
  return Object.fromEntries(entries.filter(([, value]) => value !== null));
}
